[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Frederic Desgreniers <fredericdesgreniers@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.7.11"
regex = "1.1.0"
lazy_static = "1.2.0"